// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  pages: [
    "obsidian",
    "remote-mdx",
    "github-releases",
    "sanity",
    "notion",
    "contentful",
    "payload",
    "strapi",
    "custom",
  ],
  title: "Inhaltsquellen",
};
